name: status_change
version: 2.0.0
description: Status Change Package
# author: Pesa Coder
homepage: https://github.com/UsamaElgendy/
repository: https://github.com/UsamaElgendy/status_change

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: